blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ GitHub Discussions
    url: https://github.com/tom-evoila/terraform-training/discussions
    about: Please ask and answer questions here.
  - name: ðŸ“š Documentation
    url: https://github.com/tom-evoila/terraform-training#readme
    about: Please read the documentation before reporting issues.
  - name: ðŸ™‹ Support Resources
    url: https://github.com/tom-evoila/terraform-training/blob/main/SUPPORT.md
    about: Learn how to get help and where to ask questions
  - name: ðŸ”’ Security Vulnerabilities
    url: https://github.com/tom-evoila/terraform-training/blob/main/SECURITY.md
    about: Report security vulnerabilities privately following our security policy.
